// ********RoostGPT********
/*
Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o-standard

playwright test generated for endpoint: /anything/openIdConnect, with method: post
RoostTestHash=/anything/openIdConnect-post-1bb56ade04

*/

// ********RoostGPT********

import test, { expect, request } from "@playwright/test";
import { readCsvData } from "./utility.js";

const csvFilePath = `/var/tmp/Roost/RoostGPT/roost_test/1732522522/source/oas-examples/3.0/json/playwrightApiTests/tests/General_support.csv`
const testData = await readCsvData(csvFilePath);

test("General support", async () => {
  const baseURL = "https://httpbin.org";

  for (let i = 0; i < testData.length; i++) {
    const csvDataRow = testData[i];
    const { 
      statusCode, 
      pathDesc, 
      queryDesc, 
      headerDesc, 
      cookieDesc, 
      reqBodyDesc, 
    } = csvDataRow;

    const context = await request.newContext({
      baseURL,
      extraHTTPHeaders: headerDesc,
    });

    const response = await context.post(`/anything/openIdConnect`);
    expect(response.status()).toBe(statusCode);

    if (response.status() === statusCode) {
      console.log("Response for undefined is:", await response.json());
    }
  }
});