// ********RoostGPT********
/*
Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o-standard

playwright test generated for endpoint: /anything/apiKey, with method: get
RoostTestHash=/anything/apiKey-get-1bb56ade04

*/

// ********RoostGPT********

import test, { expect, request } from "@playwright/test";
test("Query parameter", async () => {
  const baseURL = "https://httpbin.org";

  const response = await context.get("/anything/apiKey");
  
  if (response.status() === 200) {
    expect(response.status()).toBe(200);
    console.log("Response for undefined is:", await response.json());
  }
});